#########################################
### WALLET 713 CONFIGURATION          ###
#########################################

# Blockcahin to use: 'Mainnet' or 'Floonet'
# chain = "Floonet"

# Path for mwc713 wallet data
# wallet713_data_path = "wallet713_data"

# MWC MQS connection settings. By default mwc713 using thhis method for communication.
# mwcmqs_domain: mqs.mwc.mw
# mwcmqs_port: 443

# MWC MQS/GrinBox address defive index. Every new index will give you a new address that will be used for
# communication with message queue
# grinbox_address_index = 1

# MWC node connection URI. Please make sure that you are connecting to the node from correct network.
# mwc_node_uri = "https://mwc713.floonet.mwc.mw"

# MWC node secret
# mwc_node_secret = "11ne3EAUtOXVKwhxm84U"

# Start Message Queue listener automatically if wallet password was provided at start.
# grinbox_listener_auto_start = true

# Specify maximum amount in nano MWC if you want this wallet automatically accept invoices.
# Example for 5 MWCs:  max_auto_accept_invoice = 50000000000
# Note! Change it if you really understand what you are going!
# max_auto_accept_invoice =

# Enable Owner API for this wallet. See for details: https://github.com/mwcproject/mwc713/blob/master/docs/API_documentation.md
# owner_api = false

# Owner API listening address. If you want accept connections from
# the Internet, please make it "0.0.0.0:13415"
# owner_api_address = "127.0.0.1:13415"

# Owner API secret. REST API call required basic authorization with this secret (user: mwc).
# owner_api_secret = "my_secret_password"

# Include the foreign API endpoints on the same port as the owner
# API. Useful for networking environments like AWS ECS that make
# it difficult to access multiple ports on a single service.
# owner_api_include_foreign = false

# Enable Foreign API for this wallet. See for details: https://github.com/mwcproject/mwc713/blob/master/docs/API_documentation.md
# Note! Use this setting if you disable Owner API. Otherwise concider to use 'owner_api_include_foreign' setting
# foreign_api = false

# Foreign API listening address. If you want accept connections from
# the Internet, please make it "0.0.0.0:13416"
# foreign_api_address =  = "127.0.0.1:13416"

# Foreign API secret. REST API call required basic authorization with this secret (user: mwc).
# foreign_api_secret = "my_secret_password"

# Disable logging history of your mwc713 commands. Recommended for stronger security.
# Also you can disable history with command line argument '--disable-history'
# disable_history = false


# If enabled both tls_certificate_file and tls_certificate_key, TSL will be applicable to all rest API
# Paths to TLS certificate files:
# tls_certificate_file = "path to TLS certificate file"
# tls_certificate_key = "path to TLS certificate private key file"

# Wallet state update frequency. In none, no updates will be run in the background.
# If will be set, will run 'sync' command with defined time interval
# wallet_updater_frequency_sec =

# Electrum X servers that are used for Atomic Swap operations. Each Secondary Currency need
# its own dedicated Electrum X instance. We highly advise to use your own instance, instead of
# using those community servers.
# For every secondary currency expected 4 instances:
# mainnet primary, mainnet secondary, testnet primary, testnet secondary,
# Key: <coin>_[main|test]_[1|2]
# value: URI

# [wallet.swap_electrumx_addr]
# bch_main_1 = "bch.main1.swap.mwc.mw:8000"
# bch_main_2 = "bch.main2.swap.mwc.mw:8000"
# bch_test_1 = "bch.test1.swap.mwc.mw:8000"
# bch_test_2 = "bch.test2.swap.mwc.mw:8000"
# btc_main_1 = "btc.main1.swap.mwc.mw:8000"
# btc_main_2 = "btc.main2.swap.mwc.mw:8000"
# btc_test_1 = "btc.test1.swap.mwc.mw:8000"
# btc_test_2 = "btc.test1.swap.mwc.mw:8000"

chain = "Mainnet"
wallet713_data_path = "xxxxx"
default_keybase_ttl = "24h"

[swap_electrumx_addr]
bch_main_1 = "bch.main1.swap.mwc.mw:8000"
bch_main_2 = "bch.main2.swap.mwc.mw:8000"
bch_test_1 = "bch.test1.swap.mwc.mw:8000"
bch_test_2 = "bch.test1.swap.mwc.mw:8000"
btc_main_1 = "btc.main1.swap.mwc.mw:8000"
btc_main_2 = "btc.main2.swap.mwc.mw:8000"
btc_test_1 = "btc.test1.swap.mwc.mw:8000"
btc_test_2 = "btc.test2.swap.mwc.mw:8000"
